on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo TOKEN
        echo $TOKEN
      env:
        PAGES_BRANCH: gh-pages
        #BUILD_DIR: docs
        #BUILD_FLAGS: --drafts
        TOKEN: ${{ secrets.TOKEN }}
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        #BUILD_DIR: docs
        #BUILD_FLAGS: --drafts
        TOKEN: ${{ secrets.TOKEN }}
